/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleObjCpp
 *
 * We create an umbrella header (and corresponding implementation) here since
 * Cxx compilation in BUCK has a limitation: source-code producing genrule()s
 * must have a single output. More files => more genrule()s => slower builds.
 */

#ifndef __cplusplus
#error This file must be compiled as Obj-C++. If you are importing it, you must change your file extension to .mm.
#endif

// Avoid multiple includes of NativeLocationCaptureSpec symbols
#ifndef NativeLocationCaptureSpec_H
#define NativeLocationCaptureSpec_H

#import <Foundation/Foundation.h>
#import <RCTRequired/RCTRequired.h>
#import <RCTTypeSafety/RCTConvertHelpers.h>
#import <RCTTypeSafety/RCTTypedModuleConstants.h>
#import <React/RCTBridgeModule.h>
#import <React/RCTCxxConvert.h>
#import <React/RCTManagedPointer.h>
#import <ReactCommon/RCTTurboModule.h>
#import <optional>
#import <vector>


NS_ASSUME_NONNULL_BEGIN
namespace JS {
  namespace NativeLocationCapture {
    struct CaptureConfig {
      double minIntervalSec() const;
      double minDistanceM() const;
      NSString *accuracy() const;
      bool useForegroundService() const;
      NSString *notificationTitle() const;
      NSString *notificationBody() const;

      CaptureConfig(NSDictionary *const v) : _v(v) {}
    private:
      NSDictionary *_v;
    };
  }
}

@interface RCTCxxConvert (NativeLocationCapture_CaptureConfig)
+ (RCTManagedPointer *)JS_NativeLocationCapture_CaptureConfig:(id)json;
@end
@protocol NativeLocationCaptureSpec <RCTBridgeModule, RCTTurboModule>

- (void)getOrCreateStoreKeyHex:(RCTPromiseResolveBlock)resolve
                        reject:(RCTPromiseRejectBlock)reject;
- (void)getStoreDirectory:(RCTPromiseResolveBlock)resolve
                   reject:(RCTPromiseRejectBlock)reject;
- (void)initStore:(RCTPromiseResolveBlock)resolve
           reject:(RCTPromiseRejectBlock)reject;
- (void)start:(JS::NativeLocationCapture::CaptureConfig &)config
      resolve:(RCTPromiseResolveBlock)resolve
       reject:(RCTPromiseRejectBlock)reject;
- (void)stop:(RCTPromiseResolveBlock)resolve
      reject:(RCTPromiseRejectBlock)reject;
- (void)getStatus:(RCTPromiseResolveBlock)resolve
           reject:(RCTPromiseRejectBlock)reject;
- (void)requestPermission:(NSString *)step
                  resolve:(RCTPromiseResolveBlock)resolve
                   reject:(RCTPromiseRejectBlock)reject;
- (void)openSystemSettings:(NSString *)target
                   resolve:(RCTPromiseResolveBlock)resolve
                    reject:(RCTPromiseRejectBlock)reject;
- (void)getDiagnostics:(double)sinceTsUtc
               resolve:(RCTPromiseResolveBlock)resolve
                reject:(RCTPromiseRejectBlock)reject;
- (void)getDeviceConditions:(RCTPromiseResolveBlock)resolve
                     reject:(RCTPromiseRejectBlock)reject;
- (void)debugInjectSample:(double)lat
                      lon:(double)lon
                    tsUtc:(double)tsUtc
                accuracyM:(double)accuracyM
                  resolve:(RCTPromiseResolveBlock)resolve
                   reject:(RCTPromiseRejectBlock)reject;

@end

@interface NativeLocationCaptureSpecBase : NSObject {
@protected
facebook::react::EventEmitterCallback _eventEmitterCallback;
}
- (void)setEventEmitterCallback:(EventEmitterCallbackWrapper *)eventEmitterCallbackWrapper;

- (void)emitOnSampleWritten:(NSDictionary *)value;
- (void)emitOnStatusChanged:(NSDictionary *)value;
@end

namespace facebook::react {
  /**
   * ObjC++ class for module 'NativeLocationCapture'
   */
  class JSI_EXPORT NativeLocationCaptureSpecJSI : public ObjCTurboModule {
  public:
    NativeLocationCaptureSpecJSI(const ObjCTurboModule::InitParams &params);
  };
} // namespace facebook::react
inline double JS::NativeLocationCapture::CaptureConfig::minIntervalSec() const
{
  id const p = _v[@"minIntervalSec"];
  return RCTBridgingToDouble(p);
}
inline double JS::NativeLocationCapture::CaptureConfig::minDistanceM() const
{
  id const p = _v[@"minDistanceM"];
  return RCTBridgingToDouble(p);
}
inline NSString *JS::NativeLocationCapture::CaptureConfig::accuracy() const
{
  id const p = _v[@"accuracy"];
  return RCTBridgingToString(p);
}
inline bool JS::NativeLocationCapture::CaptureConfig::useForegroundService() const
{
  id const p = _v[@"useForegroundService"];
  return RCTBridgingToBool(p);
}
inline NSString *JS::NativeLocationCapture::CaptureConfig::notificationTitle() const
{
  id const p = _v[@"notificationTitle"];
  return RCTBridgingToString(p);
}
inline NSString *JS::NativeLocationCapture::CaptureConfig::notificationBody() const
{
  id const p = _v[@"notificationBody"];
  return RCTBridgingToString(p);
}
NS_ASSUME_NONNULL_END
#endif // NativeLocationCaptureSpec_H
