// GENERATED by ios/scripts/gen-contracts.mjs from packages/shared/contracts/native-writer.json,
// cipher-params.json and geo-vectors.json. Do not edit; change the contract and run the script.

/// Everything this module may do to the store (packages/shared/src/store/nativeWriter.ts).
enum StoreContract {
    static let schemaVersion = 1
    static let readSchemaVersionSql = "PRAGMA user_version"
    static let storeFileName = "findmyperson.db"
    static let insertLocationSampleSql = "INSERT INTO location_sample (ts_utc, lat, lon, accuracy_m, source, h3_r7, h3_r5) VALUES (?, ?, ?, ?, ?, ?, ?)"
    static let insertVisitStaySql = "INSERT INTO stay (start_ts, end_ts, lat, lon, radius_m, h3_r7, sample_count, closed, source) VALUES (?, ?, ?, ?, ?, ?, 0, ?, 'visit')"
    static let closeVisitStaySql = "UPDATE stay SET end_ts = ?, closed = 1 WHERE source = 'visit' AND closed = 0 AND start_ts = ?"
    static let sampleSources: [String] = ["fgs", "wm", "continuous", "slc", "visit", "region", "manual", "fetch-wake"]
}

/// The pinned SQLCipher parameters of the store (packages/shared/src/store/cipher.ts).
enum CipherParams {
    static let sqlcipherMajor = 4
    static let keyBytes = 32
    static let journalMode = "wal"
    /// Run right after the key is set and before the first read, in this order.
    static let applyPragmas: [String] = [
        "PRAGMA cipher_compatibility = 4",
        "PRAGMA cipher_page_size = 4096",
        "PRAGMA kdf_iter = 256000",
        "PRAGMA cipher_kdf_algorithm = PBKDF2_HMAC_SHA512",
        "PRAGMA cipher_hmac_algorithm = HMAC_SHA512",
    ]
    /// Pragma name and the value that must be read back after opening.
    static let readBack: [(pragma: String, expected: String)] = [
        ("cipher_page_size", "4096"),
        ("kdf_iter", "256000"),
        ("cipher_kdf_algorithm", "PBKDF2_HMAC_SHA512"),
        ("cipher_hmac_algorithm", "HMAC_SHA512"),
    ]
}

/// Constants of the shared distance function (packages/shared/src/geo/distance.ts).
enum GeoContract {
    static let earthRadiusM: Double = 6371008.8
}
