// GENERATED by scripts/gen-cipher-params.mjs from shared/cipher-params.json. Do not edit; run `npm run gen:cipher`.
enum CipherParams {
    static let sqlcipherMajor = 4
    static let cipherCompatibility = 4
    static let pageSizeBytes = 4096
    static let kdfIterations = 256000
    static let kdfAlgorithm = "PBKDF2_HMAC_SHA512"
    static let hmacAlgorithm = "HMAC_SHA512"
    static let keyFormat = "raw-hex-literal"
    static let keyBytes = 32
    static let journalMode = "wal"
    static let dbFileName = "storeproof.db"
    static let tableName = "probe_row"
    static let createTableSql = "CREATE TABLE IF NOT EXISTS probe_row (id INTEGER PRIMARY KEY, ts_utc INTEGER NOT NULL, label TEXT NOT NULL)"
    static let insertSql = "INSERT INTO probe_row (ts_utc, label) VALUES (?, ?)"
    static let selectSql = "SELECT id, ts_utc, label FROM probe_row ORDER BY id"
    static let applyPragmas: [String] = [
        "PRAGMA cipher_compatibility = 4",
        "PRAGMA cipher_page_size = 4096",
        "PRAGMA kdf_iter = 256000",
        "PRAGMA cipher_kdf_algorithm = PBKDF2_HMAC_SHA512",
        "PRAGMA cipher_hmac_algorithm = HMAC_SHA512",
    ]
    static let readBack: [(pragma: String, expected: String)] = [
        ("cipher_page_size", "4096"),
        ("kdf_iter", "256000"),
        ("cipher_kdf_algorithm", "PBKDF2_HMAC_SHA512"),
        ("cipher_hmac_algorithm", "HMAC_SHA512"),
    ]
    static let keyVectorHex = "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"
    static let keyVectorLiteral = "x'000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f'"
}
