#import <NativeLocationCaptureSpec/NativeLocationCaptureSpec.h>

// The Turbo Native Module for src/specs/NativeLocationCapture.ts. The protocol and the base
// class are generated by React Native's codegen from that file; a committed copy is
// contracts/ios/NativeLocationCaptureSpec.h. package.json (codegenConfig.ios.modulesProvider)
// maps the JavaScript name NativeLocationCapture to this class.
@interface RCTNativeLocationCapture : NativeLocationCaptureSpecBase <NativeLocationCaptureSpec>
@end
