// GENERATED by scripts/gen-cipher-params.mjs from shared/cipher-params.json. Do not edit; run `npm run gen:cipher`.
package com.storeproof.store

object CipherParams {
    const val SQLCIPHER_MAJOR = 4
    const val CIPHER_COMPATIBILITY = 4
    const val PAGE_SIZE_BYTES = 4096
    const val KDF_ITERATIONS = 256000
    const val KDF_ALGORITHM = "PBKDF2_HMAC_SHA512"
    const val HMAC_ALGORITHM = "HMAC_SHA512"
    const val KEY_FORMAT = "raw-hex-literal"
    const val KEY_BYTES = 32
    const val JOURNAL_MODE = "wal"
    const val DB_FILE_NAME = "storeproof.db"
    const val TABLE_NAME = "probe_row"
    const val CREATE_TABLE_SQL = "CREATE TABLE IF NOT EXISTS probe_row (id INTEGER PRIMARY KEY, ts_utc INTEGER NOT NULL, label TEXT NOT NULL)"
    const val INSERT_SQL = "INSERT INTO probe_row (ts_utc, label) VALUES (?, ?)"
    const val SELECT_SQL = "SELECT id, ts_utc, label FROM probe_row ORDER BY id"
    val APPLY_PRAGMAS: List<String> = listOf(
        "PRAGMA cipher_compatibility = 4",
        "PRAGMA cipher_page_size = 4096",
        "PRAGMA kdf_iter = 256000",
        "PRAGMA cipher_kdf_algorithm = PBKDF2_HMAC_SHA512",
        "PRAGMA cipher_hmac_algorithm = HMAC_SHA512",
    )
    val READ_BACK: List<Pair<String, String>> = listOf(
        "cipher_page_size" to "4096",
        "kdf_iter" to "256000",
        "cipher_kdf_algorithm" to "PBKDF2_HMAC_SHA512",
        "cipher_hmac_algorithm" to "HMAC_SHA512",
    )
    const val KEY_VECTOR_HEX = "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"
    const val KEY_VECTOR_LITERAL = "x'000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f'"
}
