
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleJavaSpec.js
 *
 * @nolint
 */

package dev.findmyperson.locationcapture;

import com.facebook.proguard.annotations.DoNotStrip;
import com.facebook.react.bridge.Promise;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;
import com.facebook.react.bridge.ReadableMap;
import com.facebook.react.turbomodule.core.interfaces.TurboModule;
import javax.annotation.Nonnull;

public abstract class NativeLocationCaptureSpec extends ReactContextBaseJavaModule implements TurboModule {
  public static final String NAME = "NativeLocationCapture";

  public NativeLocationCaptureSpec(ReactApplicationContext reactContext) {
    super(reactContext);
  }

  @Override
  public @Nonnull String getName() {
    return NAME;
  }

  protected final void emitOnSampleWritten(ReadableMap value) {
    mEventEmitterCallback.invoke("onSampleWritten", value);
  }

  protected final void emitOnStatusChanged(ReadableMap value) {
    mEventEmitterCallback.invoke("onStatusChanged", value);
  }

  @ReactMethod
  @DoNotStrip
  public abstract void getOrCreateStoreKeyHex(Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void getStoreDirectory(Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void initStore(Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void start(ReadableMap config, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void stop(Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void getStatus(Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void requestPermission(String step, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void openSystemSettings(String target, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void getDiagnostics(double sinceTsUtc, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void getDeviceConditions(Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void debugInjectSample(double lat, double lon, double tsUtc, double accuracyM, Promise promise);
}
