// GENERATED by packages/encrypted-store/src/nativeContract.ts from @findmyperson/shared.
// Do not edit. Change the TypeScript source, then run from the repo root:
//   pnpm exec vitest run packages/encrypted-store -u
package dev.findmyperson.encryptedstore

object StoreContract {
    const val SQLCIPHER_MAJOR = 4
    const val KEY_BYTES = 32
    const val JOURNAL_MODE = "wal"
    val APPLY_PRAGMAS: List<String> = listOf(
        "PRAGMA cipher_compatibility = 4",
        "PRAGMA cipher_page_size = 4096",
        "PRAGMA kdf_iter = 256000",
        "PRAGMA cipher_kdf_algorithm = PBKDF2_HMAC_SHA512",
        "PRAGMA cipher_hmac_algorithm = HMAC_SHA512",
    )
    val READ_BACK: List<Pair<String, String>> = listOf(
        "cipher_page_size" to "4096",
        "kdf_iter" to "256000",
        "cipher_kdf_algorithm" to "PBKDF2_HMAC_SHA512",
        "cipher_hmac_algorithm" to "HMAC_SHA512",
    )
    const val BUSY_TIMEOUT_MS = 5000
    const val KEY_VECTOR_HEX = "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"
    const val KEY_VECTOR_LITERAL = "x'000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f'"
    const val STORE_FILE_NAME = "findmyperson.db"
    val STORE_FILE_SUFFIXES: List<String> = listOf(
        "",
        "-wal",
        "-shm",
    )
    const val SCHEMA_VERSION = 1
    const val READ_SCHEMA_VERSION_SQL = "PRAGMA user_version"
    const val INSERT_LOCATION_SAMPLE_SQL = "INSERT INTO location_sample (ts_utc, lat, lon, accuracy_m, source, h3_r7, h3_r5) VALUES (?, ?, ?, ?, ?, ?, ?)"
    val SAMPLE_SOURCES: List<String> = listOf(
        "fgs",
        "wm",
        "continuous",
        "slc",
        "visit",
        "region",
        "manual",
        "fetch-wake",
    )
    const val INSERT_VISIT_STAY_SQL = "INSERT INTO stay (start_ts, end_ts, lat, lon, radius_m, h3_r7, sample_count, closed, source) VALUES (?, ?, ?, ?, ?, ?, 0, ?, 'visit')"
    const val CLOSE_VISIT_STAY_SQL = "UPDATE stay SET end_ts = ?, closed = 1 WHERE source = 'visit' AND closed = 0 AND start_ts = ?"
    const val RETENTION_SEC = 2592000
    const val DELETE_SAMPLES_BEFORE_SQL = "DELETE FROM location_sample WHERE ts_utc < ?"
    const val DELETE_STAYS_ENDED_BEFORE_SQL = "DELETE FROM stay WHERE end_ts < ?"
    const val TRIM_STAYS_STARTED_BEFORE_SQL = "UPDATE stay SET start_ts = ? WHERE start_ts < ? AND end_ts >= ?"
    const val REWIND_STAY_CURSOR_SQL = "UPDATE kv SET v = (SELECT CAST(coalesce(max(id), 0) AS TEXT) FROM location_sample) WHERE k = 'stay_derivation.last_sample_id' AND CAST(v AS INTEGER) > (SELECT coalesce(max(id), 0) FROM location_sample)"
    const val STORE_DIRECTORY_NAME = "fmp-store"
    const val KEY_FILE_NAME = "store-key.wrapped"
    const val KEYSTORE_ALIAS = "fmp_store_wrap_v1"
}
