package dev.findmyperson.encryptedstore

import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.module.annotations.ReactModule
import java.util.concurrent.Executors

/**
 * Turbo Native Module for src/specs/NativeEncryptedStore.ts. The spec class
 * (NativeEncryptedStoreSpec) is generated by React Native's codegen at build time; a committed
 * copy is in contracts/android/. Everything it does is one call into [EncryptedStore].
 */
@ReactModule(name = EncryptedStoreModule.NAME)
class EncryptedStoreModule(reactContext: ReactApplicationContext) : NativeEncryptedStoreSpec(reactContext) {
    // Off the JS and UI threads: the Keystore and the file system are blocking.
    private val io = Executors.newSingleThreadExecutor()
    private val store = EncryptedStore.get(reactContext)

    override fun getName() = NAME

    override fun getOrCreateStoreKeyHex(promise: Promise) = answer(promise) { store.keyHex() }

    override fun getStoreDirectory(promise: Promise) = answer(promise) { store.directory().absolutePath }

    override fun deleteAllData(promise: Promise) = answer(promise) {
        store.deleteAllData()
        null
    }

    private fun answer(promise: Promise, work: () -> Any?) {
        io.execute {
            try {
                promise.resolve(work())
            } catch (e: StoreException) {
                promise.reject(e.code.lowercase(), e.message, e)
            } catch (e: Exception) {
                promise.reject("store_failed", e.message, e)
            }
        }
    }

    companion object {
        const val NAME = "NativeEncryptedStore"
    }
}
