// GENERATED by packages/encrypted-store/src/nativeContract.ts from @findmyperson/shared.
// Do not edit. Change the TypeScript source, then run from the repo root:
//   pnpm exec vitest run packages/encrypted-store -u
public enum StoreContract {
    public static let sqlcipherMajor = 4
    public static let keyBytes = 32
    public static let journalMode = "wal"
    public static let applyPragmas: [String] = [
        "PRAGMA cipher_compatibility = 4",
        "PRAGMA cipher_page_size = 4096",
        "PRAGMA kdf_iter = 256000",
        "PRAGMA cipher_kdf_algorithm = PBKDF2_HMAC_SHA512",
        "PRAGMA cipher_hmac_algorithm = HMAC_SHA512",
    ]
    public static let readBack: [(pragma: String, expected: String)] = [
        ("cipher_page_size", "4096"),
        ("kdf_iter", "256000"),
        ("cipher_kdf_algorithm", "PBKDF2_HMAC_SHA512"),
        ("cipher_hmac_algorithm", "HMAC_SHA512"),
    ]
    public static let busyTimeoutMs = 5000
    public static let keyVectorHex = "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f"
    public static let keyVectorLiteral = "x'000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f'"
    public static let storeDirectoryName = "fmp-store"
    public static let storeFileName = "findmyperson.db"
    public static let storeFileSuffixes: [String] = [
        "",
        "-wal",
        "-shm",
    ]
    public static let schemaVersion = 1
    public static let readSchemaVersionSql = "PRAGMA user_version"
    public static let insertLocationSampleSql = "INSERT INTO location_sample (ts_utc, lat, lon, accuracy_m, source, h3_r7, h3_r5) VALUES (?, ?, ?, ?, ?, ?, ?)"
    public static let sampleSources: [String] = [
        "fgs",
        "wm",
        "continuous",
        "slc",
        "visit",
        "region",
        "manual",
        "fetch-wake",
    ]
    public static let insertVisitStaySql = "INSERT INTO stay (start_ts, end_ts, lat, lon, radius_m, h3_r7, sample_count, closed, source) VALUES (?, ?, ?, ?, ?, ?, 0, ?, 'visit')"
    public static let closeVisitStaySql = "UPDATE stay SET end_ts = ?, closed = 1 WHERE source = 'visit' AND closed = 0 AND start_ts = ?"
    public static let keychainService = "dev.findmyperson.store"
    public static let keychainAccount = "store-key-v1"
}
