import {
  buildApplyPragmas,
  buildReadBack,
  CIPHER_KEY_VECTOR,
  CIPHER_PARAMS,
  NATIVE_WRITER_CONTRACT,
} from '@findmyperson/shared';
import {
  ANDROID_KEY_FILE_NAME,
  ANDROID_KEYSTORE_ALIAS,
  ANDROID_STORE_DIRECTORY_NAME,
  IOS_KEYCHAIN_ACCOUNT,
  IOS_KEYCHAIN_SERVICE,
  IOS_STORE_DIRECTORY_NAME,
  STORE_FILE_SUFFIXES,
} from './location';
import { STORE_BUSY_TIMEOUT_MS } from './openStore';

/**
 * Kotlin and Swift cannot import TypeScript, so the constants they need are written out as one
 * source file per language: android/.../StoreContract.kt and ios/StoreContract.swift.
 *
 * Nothing here is a new definition. The cipher parameters and the SQL come from
 * @findmyperson/shared (CIPHER_PARAMS, NATIVE_WRITER_CONTRACT), the rest from ./location.ts and
 * ./openStore.ts. nativeContract.test.ts fails when a committed file differs from what this
 * renders; `pnpm exec vitest run packages/encrypted-store -u`, from the repo root, rewrites
 * them. Not exported from the package: only that test calls it.
 */

type Value = string | number | readonly string[] | ReadonlyArray<readonly [string, string]>;

/** Every constant, in file order. Names are UPPER_SNAKE here; Swift gets lowerCamel. */
export function nativeConstants(): Array<[name: string, value: Value]> {
  const cipher = CIPHER_PARAMS;
  const writer = NATIVE_WRITER_CONTRACT;
  return [
    ['SQLCIPHER_MAJOR', cipher.sqlcipherMajor],
    ['KEY_BYTES', cipher.keyBytes],
    ['JOURNAL_MODE', cipher.journalMode],
    ['APPLY_PRAGMAS', buildApplyPragmas()],
    ['READ_BACK', buildReadBack()],
    ['BUSY_TIMEOUT_MS', STORE_BUSY_TIMEOUT_MS],
    ['KEY_VECTOR_HEX', CIPHER_KEY_VECTOR.hex],
    ['KEY_VECTOR_LITERAL', CIPHER_KEY_VECTOR.literal],
    ['STORE_FILE_NAME', writer.storeFileName],
    ['STORE_FILE_SUFFIXES', STORE_FILE_SUFFIXES],
    ['SCHEMA_VERSION', writer.schemaVersion],
    ['READ_SCHEMA_VERSION_SQL', writer.readSchemaVersionSql],
    ['INSERT_LOCATION_SAMPLE_SQL', writer.insertLocationSampleSql],
    ['SAMPLE_SOURCES', writer.sampleSources],
    ['INSERT_VISIT_STAY_SQL', writer.insertVisitStaySql],
    ['CLOSE_VISIT_STAY_SQL', writer.closeVisitStaySql],
    ['RETENTION_SEC', writer.retentionSec],
    ['DELETE_SAMPLES_BEFORE_SQL', writer.deleteSamplesBeforeSql],
    ['DELETE_STAYS_ENDED_BEFORE_SQL', writer.deleteStaysEndedBeforeSql],
    ['TRIM_STAYS_STARTED_BEFORE_SQL', writer.trimStaysStartedBeforeSql],
    ['REWIND_STAY_CURSOR_SQL', writer.rewindStayCursorSql],
  ];
}

const ANDROID_ONLY: Array<[string, Value]> = [
  ['STORE_DIRECTORY_NAME', ANDROID_STORE_DIRECTORY_NAME],
  ['KEY_FILE_NAME', ANDROID_KEY_FILE_NAME],
  ['KEYSTORE_ALIAS', ANDROID_KEYSTORE_ALIAS],
];

const IOS_ONLY: Array<[string, Value]> = [
  ['STORE_DIRECTORY_NAME', IOS_STORE_DIRECTORY_NAME],
  ['KEYCHAIN_SERVICE', IOS_KEYCHAIN_SERVICE],
  ['KEYCHAIN_ACCOUNT', IOS_KEYCHAIN_ACCOUNT],
];

const HEADER = [
  'GENERATED by packages/encrypted-store/src/nativeContract.ts from @findmyperson/shared.',
  'Do not edit. Change the TypeScript source, then run from the repo root:',
  '  pnpm exec vitest run packages/encrypted-store -u',
];

// JSON string syntax is valid Kotlin and Swift for these values, except that Kotlin reads `$`
// as the start of a template.
const quote = (text: string, escapeDollar: boolean) =>
  escapeDollar ? JSON.stringify(text).replaceAll('$', '\\$') : JSON.stringify(text);

const isPairs = (value: Value): value is ReadonlyArray<readonly [string, string]> =>
  Array.isArray(value) && Array.isArray(value[0]);

export function renderKotlin(packageName: string): string {
  const q = (text: string) => quote(text, true);
  const lines = [...nativeConstants(), ...ANDROID_ONLY].map(([name, value]) => {
    if (typeof value === 'number') {
      return `    const val ${name} = ${value}`;
    }
    if (typeof value === 'string') {
      return `    const val ${name} = ${q(value)}`;
    }
    const items = isPairs(value)
      ? value.map(([key, expected]) => `        ${q(key)} to ${q(expected)},`)
      : (value as readonly string[]).map((item) => `        ${q(item)},`);
    const type = isPairs(value) ? 'List<Pair<String, String>>' : 'List<String>';
    return [`    val ${name}: ${type} = listOf(`, ...items, '    )'].join('\n');
  });
  return [
    ...HEADER.map((line) => `// ${line}`),
    `package ${packageName}`,
    '',
    'object StoreContract {',
    ...lines,
    '}',
    '',
  ].join('\n');
}

const camel = (name: string) =>
  name.toLowerCase().replace(/_([a-z0-9])/g, (_, letter: string) => letter.toUpperCase());

export function renderSwift(): string {
  const q = (text: string) => quote(text, false);
  const lines = [...nativeConstants(), ...IOS_ONLY].map(([name, value]) => {
    if (typeof value === 'number') {
      return `    public static let ${camel(name)} = ${value}`;
    }
    if (typeof value === 'string') {
      return `    public static let ${camel(name)} = ${q(value)}`;
    }
    const items = isPairs(value)
      ? value.map(([key, expected]) => `        (${q(key)}, ${q(expected)}),`)
      : (value as readonly string[]).map((item) => `        ${q(item)},`);
    const type = isPairs(value) ? '[(pragma: String, expected: String)]' : '[String]';
    return [`    public static let ${camel(name)}: ${type} = [`, ...items, '    ]'].join('\n');
  });
  return [
    ...HEADER.map((line) => `// ${line}`),
    'public enum StoreContract {',
    ...lines,
    '}',
    '',
  ].join('\n');
}
